name: update-status

on:
  schedule:
    # Runs at 24:00 Beijing (UTC + 8) 
    - cron: "0 16 * * *"  
workflow_dispatch:
jobs:
  update-readme:
    name: Update Wakatime status
    runs-on: ubuntu-latest
    steps:              
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_UPDATED_DATE: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_LOC_CHART: "False"
          SYMBOL_VERSION: 3
